import invariant from 'tiny-invariant'

import {
  CabinetDef,
  CabinetID,
  CategoryKeys,
  GridCategoryDef,
  ShelfDef,
} from '@/app/u/[username]/bar/lib/types'

export function getCabinetDef(keys: CategoryKeys): CabinetDef {
  const { cabinet } = keys
  invariant(cabinet, 'Cabinet ID required to get cabinet def')
  const cabinetDef = DEFS[cabinet as CabinetID]
  invariant(cabinetDef, `Cabinet '${cabinet}' not found`)
  return { ...cabinetDef, keys }
}

export function getShelfDef(keys: CategoryKeys): ShelfDef {
  const { shelf } = keys
  invariant(shelf, 'Shelf ID required to get shelf def')
  const cabinetDef = getCabinetDef(keys)
  const shelfDef = cabinetDef?.children?.[shelf]
  invariant(shelfDef, `Shelf '${shelf}' not found`)
  return { ...shelfDef, keys }
}

export function getCategoryDef(keys: CategoryKeys): GridCategoryDef {
  const { category } = keys
  invariant(category, 'Category ID required to get category def')
  const shelfDef = getShelfDef(keys)
  const categoryDef = shelfDef.children[category]
  invariant(categoryDef, `Category '${category}' not found`)
  return { ...categoryDef, keys }
}

export const SAMPLE_DEFS: Record<CabinetID[0], Omit<CabinetDef, 'keys'>> = {
  essentials: {
    name: 'Bar Essentials',
    gridIDs: ['core-spirits'],
    listIDs: ['core-spirits'],
    children: {
      'core-spirits': {
        name: 'Core Spirits',
        gridCols: 12,
        gridIDs: [
          'rye-whiskey',
          'dry-gin',
          'sweet-vermouth',
          'dry-vermouth',
          'cognac',
          'maraschino',
          'angostura',
          'campari',
          'peychauds',
        ],
        listIDs: [],
        children: {
          'rye-whiskey': {
            name: 'Rye Whiskey',
            colSpan: 6,
            items: 3,
            include: [{ id: 'grain_whiskey_rye' }],
          },
          'dry-gin': {
            name: 'Dry Gin',
            colSpan: 6,
            items: 3,
            include: [
              { id: 'grain_gin_londondry' },
              { id: 'grain_gin_contemporary' },
              { id: 'grain_gin_plymouth' },
            ],
          },
          'sweet-vermouth': {
            name: 'Sweet Vermouth',
            colSpan: 6,
            items: 1,
            include: [{ id: 'fortifiedwine_sweetvermouth' }],
          },
          'dry-vermouth': {
            name: 'Dry Vermouth',
            colSpan: 6,
            items: 1,
            include: [{ id: 'fortifiedwine_dryvermouth' }],
          },
          cognac: {
            name: 'Cognac/Brandy',
            colSpan: 4,
            items: 3,
            include: [
              { id: 'brandy_grape_cognac' },
              { id: 'brandy_grape_armagnac' },
              { id: 'brandy_grape_american' },
            ],
          },
          maraschino: {
            name: 'Maraschino',
            include: [{ id: 'liqueur_maraschino' }],
            colSpan: 4,
            hideGridItems: true,
          },
          angostura: {
            name: 'Angostura',
            items: 1,
            colSpan: 4,
            ids: ['angostura'],
            hideItems: true,
          },
          campari: {
            name: 'Campari',
            items: 1,
            colSpan: 4,
            ids: [
              'campari',
              'gran_classico_bitter',
              'st_george_bruto_americano',
            ],
            hideGridItems: true,
          },
          peychauds: {
            name: 'Peychauds',
            colSpan: 4,
            ids: ['peychauds'],
            hideItems: true,
          },
        },
      },
    },
  },
}

export const DEFS: Record<CabinetID, Omit<CabinetDef, 'keys'>> = {
  essentials: {
    name: 'Bar Essentials',
    gridIDs: [
      'core-spirits',
      'classic-spirits',
      'modern-classics',
      'sweeteners',
      'citrus',
      'lengtheners',
    ],
    listIDs: [
      'core-spirits',
      'classic-spirits',
      'modern-classics',
      'sweeteners',
      'citrus',
      'lengtheners',
    ],
    children: {
      'core-spirits': {
        name: 'Core Spirits',
        gridCols: 2,
        gridIDs: ['rye-whiskey', 'dry-gin', 'sweet-vermouth', 'dry-vermouth'],
        listIDs: ['rye-whiskey', 'dry-gin', 'sweet-vermouth', 'dry-vermouth'],
        children: {
          'rye-whiskey': {
            name: 'Rye Whiskey',
            items: 3,
            include: [{ id: 'grain_whiskey_rye' }],
          },
          'dry-gin': {
            name: 'Dry Gin',
            items: 3,
            include: [
              { id: 'grain_gin_londondry' },
              { id: 'grain_gin_contemporary' },
              { id: 'grain_gin_plymouth' },
            ],
          },
          'sweet-vermouth': {
            name: 'Sweet Vermouth',
            items: 1,
            include: [{ id: 'fortifiedwine_sweetvermouth' }],
          },
          'dry-vermouth': {
            name: 'Dry Vermouth',
            items: 1,
            include: [{ id: 'fortifiedwine_dryvermouth' }],
          },
        },
      },
      'classic-spirits': {
        name: 'Classic Spirits',
        gridCols: 3,
        gridIDs: [
          'cognac',
          'maraschino',
          'angostura',
          'campari',
          'peychauds',
          'apple-brandy',
          'orange-liqueur',
          'orange-bitters',
          'bitters-and-shrubs',
          'benedictine',
          'absinthe',
          'green-chartreuse',
        ],
        listIDs: [
          'cognac',
          'apple-brandy',
          'absinthe',
          'maraschino',
          'campari',
          'orange-liqueur',
          'benedictine',
          'green-chartreuse',
          'angostura',
          'peychauds',
          'orange-bitters',
          'bitters-and-shrubs',
        ],
        children: {
          cognac: {
            name: 'Cognac/Brandy',
            items: 3,
            include: [
              { id: 'brandy_grape_cognac' },
              { id: 'brandy_grape_armagnac' },
              { id: 'brandy_grape_american' },
            ],
          },
          maraschino: {
            name: 'Maraschino',
            include: [{ id: 'liqueur_maraschino' }],
            hideGridItems: true,
          },
          angostura: {
            name: 'Angostura',
            items: 1,
            ids: ['angostura'],
            hideItems: true,
          },
          campari: {
            name: 'Campari',
            items: 1,
            ids: [
              'campari',
              'gran_classico_bitter',
              'st_george_bruto_americano',
            ],
            hideGridItems: true,
          },
          peychauds: {
            name: 'Peychauds',
            ids: ['peychauds'],
            hideItems: true,
          },
          'apple-brandy': {
            name: 'Apple Brandy',
            items: 2,
            include: [{ id: 'brandy_apple' }],
          },
          'orange-liqueur': {
            name: 'Orange Liqueur',
            items: 1,
            include: [{ id: 'liqueur_orange' }],
          },
          'orange-bitters': {
            name: 'Orange Bitters',
            include: [{ id: 'bitters_orange' }],
          },
          'bitters-and-shrubs': {
            name: 'Other Bitters',
            items: 3,
            include: [{ id: 'bitters' }],
            exclude: [{ id: 'bitters_orange' }],
            excludeIDs: ['angostura', 'peychauds'],
            disableOneClickEmpty: true,
          },
          benedictine: {
            name: 'Bénédictine',
            ids: ['benedictine'],
            hideItems: true,
          },
          absinthe: {
            name: 'Absinthe',
            items: 1,
            include: [{ id: 'liqueur_absinthe' }],
          },
          'green-chartreuse': {
            name: 'Green Chartreuse',
            ids: ['green_chartreuse'],
            hideItems: true,
          },
        },
      },
      'modern-classics': {
        name: 'Modern Classics',
        gridCols: 3,
        gridIDs: [
          'bourbon',
          'yellow-chartreuse',
          'aperitivo-bianco',
          'cynar',
          'aperitif-blanc',
          'mezcal',
          'fernet',
          'vin-de-liqueur',
          'tequila-blanco',
          'dry-sherry',
          'elderflower',
        ],
        listIDs: [
          'bourbon',
          'mezcal',
          'tequila-blanco',
          'yellow-chartreuse',
          'cynar',
          'fernet',
          'dry-sherry',
          'aperitivo-bianco',
          'aperitif-blanc',
          'vin-de-liqueur',
          'elderflower',
        ],
        children: {
          bourbon: {
            name: 'Bourbon',
            items: 2,
            include: [{ id: 'grain_whiskey_bourbon' }],
          },
          'yellow-chartreuse': {
            name: 'Yellow Chartreuse',
            ids: ['yellow_chartreuse'],
            hideItems: true,
          },
          'aperitivo-bianco': {
            name: 'Aperitivo Bianco',
            items: 1,
            include: [{ id: 'liqueur_amaro_aperitivo' }],
            excludeIDs: [
              'aperol',
              'campari',
              'gran_classico_bitter',
              'st_george_bruto_americano',
            ],
            bottlesOnly: true,
          },
          cynar: {
            name: 'Cynar',
            items: 1,
            ids: ['cynar'],
            hideItems: true,
          },
          'aperitif-blanc': {
            name: 'Apéritif Blanc',
            items: 1,
            include: [{ id: 'fortifiedwine_blancvermouth' }],
            ids: [
              'lillet_blanc',
              'cocchi_americano_bianco',
              'cap_corse_blanc_quinquina',
            ],
            bottlesOnly: true,
          },
          mezcal: {
            name: 'Mezcal',
            items: 2,
            include: [{ id: 'agave_mezcal' }],
          },
          fernet: {
            name: 'Fernet',
            items: 1,
            include: [{ id: 'liqueur_amaro_fernet' }],
          },
          'vin-de-liqueur': {
            name: 'Vin de Liqueur',
            items: 1,
            include: [
              { id: 'brandy_grape_pineaudescharentes' },
              { id: 'brandy_grape_pommeau' },
              { id: 'fortifiedwine_mistelle' },
            ],
          },
          'tequila-blanco': {
            name: 'Tequila Blanco',
            items: 1,
            include: [{ id: 'agave_tequila_blanco' }],
          },
          'dry-sherry': {
            name: 'Dry Sherry',
            items: 1,
            include: [
              { id: 'fortifiedwine_sherry_fino' },
              { id: 'fortifiedwine_sherry_manzanilla' },
              { id: 'fortifiedwine_sherry_amontillado' },
            ],
          },
          elderflower: {
            name: 'Elderflower',
            include: [{ id: 'liqueur_elderflower' }],
            hideGridItems: true,
          },
        },
      },
      sweeteners: {
        name: 'Sweeteners',
        gridCols: 4,
        gridIDs: [
          'simple-syrup',
          'demerara-syrup',
          'honey',
          'maple',
          'grenadine',
          'agave',
        ],
        listIDs: [
          'simple-syrup',
          'demerara-syrup',
          'honey',
          'maple',
          'grenadine',
          'agave',
        ],
        flatList: true,
        children: {
          'simple-syrup': {
            name: 'Simple Syrup',
            items: 2,
            include: [{ id: 'syrup_simple' }],
            hideItems: true,
          },
          'demerara-syrup': {
            name: 'Demerara Syrup',
            items: 2,
            include: [{ id: 'syrup_demerara' }],
            hideItems: true,
          },
          honey: {
            name: 'Honey',
            include: [{ id: 'syrup_honey' }],
            hideItems: true,
          },
          maple: {
            name: 'Maple',
            include: [{ id: 'syrup_maple' }],
            hideItems: true,
          },
          grenadine: {
            name: 'Grenadine',
            include: [{ id: 'syrup_grenadine' }],
            hideItems: true,
          },
          agave: {
            name: 'Agave',
            include: [{ id: 'syrup_agave' }],
            hideItems: true,
          },
        },
      },
      citrus: {
        name: 'Citrus',
        gridCols: 3,
        gridIDs: [
          'lemon-juice',
          'lime-juice',
          'grapefruit-juice',
          'orange-juice',
        ],
        listIDs: [
          'lemon-juice',
          'lime-juice',
          'grapefruit-juice',
          'orange-juice',
        ],
        flatList: true,
        children: {
          'lemon-juice': {
            name: 'Lemon Juice',
            items: 2,
            include: [{ id: 'juice_lemon' }],
            hideItems: true,
          },
          'lime-juice': {
            name: 'Lime Juice',
            items: 2,
            include: [{ id: 'juice_lime' }],
            hideItems: true,
          },
          'grapefruit-juice': {
            name: 'Grapefruit Juice',
            include: [{ id: 'juice_grapefruit' }],
            hideItems: true,
          },
          'orange-juice': {
            name: 'Orange Juice',
            include: [{ id: 'juice_orange' }],
            hideItems: true,
          },
        },
      },
      lengtheners: {
        name: 'Lengtheners',
        gridCols: 12,
        gridIDs: [
          'club-soda',
          'tonic-water',
          'champagne',
          'coffee',
          'cream',
          'ginger-beer',
          'mint',
          'egg',
        ],
        listIDs: [
          'club-soda',
          'tonic-water',
          'champagne',
          'coffee',
          'cream',
          'ginger-beer',
          'mint',
          'egg',
        ],
        flatList: true,
        children: {
          'club-soda': {
            name: 'Club Soda',
            colSpan: 2,
            items: 2,
            include: [{ id: 'soda_club' }],
            hideItems: true,
          },
          'tonic-water': {
            name: 'Tonic Water',
            colSpan: 2,
            items: 2,
            include: [{ id: 'soda_tonic' }],
            hideItems: true,
          },
          champagne: {
            name: 'Champagne',
            colSpan: 3,
            include: [{ id: 'wine_sparkling' }],
            hideItems: true,
          },
          coffee: {
            name: 'Coffee',
            colSpan: 3,
            include: [{ id: 'coffee_hot' }],
            hideItems: true,
          },
          cream: {
            name: 'Cream',
            colSpan: 2,
            include: [{ id: 'cream_heavy' }],
            hideItems: true,
          },
          'ginger-beer': {
            name: 'Ginger Beer',
            colSpan: 3,
            include: [{ id: 'soda_gingerbeer' }],
            hideItems: true,
          },
          mint: {
            name: 'Mint',
            colSpan: 3,
            include: [{ id: 'spice_mint' }],
            hideItems: true,
          },
          egg: {
            name: 'Egg',
            colSpan: 2,
            include: [{ id: 'egg_whole' }],
            hideItems: true,
          },
        },
      },
    },
  },
  tiki: {
    name: 'Tiki Room',
    gridIDs: ['cane-spirits', 'tiki-liqueurs', 'tiki-pantry'],
    listIDs: ['cane-spirits', 'tiki-liqueurs', 'tiki-pantry'],
    children: {
      'cane-spirits': {
        name: 'Cane Spirits',
        gridCols: 2,
        gridIDs: [
          'jamaican-rum',
          'smith-and-cross',
          'wray-and-nephew',
          'black-rum',
          'demerara-rum',
          'overproof-rum',
          'cachaca',
          'rhum-agricole',
          'clairin',
          'other-rum',
          'batavia-arrack',
          'swedish-punsch',
        ],
        listIDs: [
          'smith-and-cross',
          'wray-and-nephew',
          'jamaican-rum',
          'demerara-rum',
          'black-rum',
          'overproof-rum',
          'rhum-agricole',
          'other-rum',
          'clairin',
          'cachaca',
          'batavia-arrack',
          'swedish-punsch',
        ],
        flatList: true,
        children: {
          'jamaican-rum': {
            name: 'Jamaican Rum',
            items: 4,
            include: [{ id: 'cane_rum_jamaican', black: false }],
            excludeIDs: ['smith_cross_navy_strength', 'wray_nephew_overproof'],
          },
          'smith-and-cross': {
            name: 'Smith & Cross',
            ids: ['smith_cross_navy_strength'],
            hideItems: true,
          },
          'wray-and-nephew': {
            name: 'Wray & Nephew',
            ids: ['wray_nephew_overproof'],
            hideItems: true,
          },
          'black-rum': {
            name: 'Black Rum',
            items: 1,
            include: [{ id: 'cane_rum', black: true, overproof: false }],
            bottlesOnly: true,
          },
          'demerara-rum': {
            name: 'Demerara Rum',
            items: 3,
            include: [
              { id: 'cane_rum_demerara', overproof: false, black: false },
            ],
          },
          'overproof-rum': {
            name: 'Overproof Rum',
            items: 1,
            include: [{ id: 'cane_rum', black: true, overproof: true }],
            bottlesOnly: true,
          },
          cachaca: {
            name: 'Cachaça',
            items: 1,
            include: [{ id: 'cane_cachaca' }],
          },
          'rhum-agricole': {
            name: 'Rhum Agricole',
            items: 2,
            include: [
              { id: 'cane_rum_agricole', overproof: false, black: false },
            ],
          },
          clairin: {
            name: 'Clairin',
            items: 1,
            include: [{ id: 'cane_clairin' }],
          },
          'other-rum': {
            name: 'Other Rum',
            items: 5,
            include: [{ id: 'cane_rum' }],
            exclude: [
              { id: 'cane_rum', black: true },
              { id: 'cane_rum', overproof: true },
              { id: 'cane_rum_jamaican', black: false },
              { id: 'cane_rum_demerara', overproof: false, black: false },
              { id: 'cane_rum_agricole' },
            ],
            disableOneClickEmpty: true,
          },
          'batavia-arrack': {
            name: 'Batavia Arrack',
            items: 1,
            include: [{ id: 'cane_bataviaarrack' }],
          },
          'swedish-punsch': {
            name: 'Swedish Punsch',
            items: 1,
            include: [{ id: 'cane_swedishpunsch' }],
          },
        },
      },
      'tiki-liqueurs': {
        name: 'Tiki Liqueurs',
        gridCols: 3,
        gridIDs: ['falernum', 'allspice-dram', 'cherry-heering'],
        listIDs: ['falernum', 'allspice-dram', 'cherry-heering'],
        children: {
          falernum: {
            name: 'Falernum',
            items: 1,
            ids: ['john_d_taylors_velvet_falernum'],
            hideItems: true,
          },
          'allspice-dram': {
            name: 'Allspice Dram',
            items: 1,
            ids: ['st_elizabeth_allspice_dram'],
            hideItems: true,
          },
          'cherry-heering': {
            name: 'Cherry Heering',
            items: 1,
            include: [{ id: 'liqueur_cherryheering' }],
          },
        },
      },
      'tiki-pantry': {
        name: 'Tiki Pantry',
        gridCols: 12,
        gridIDs: [
          'pineapple-juice',
          'orgeat',
          'cinnamon-syrup',
          'passion-fruit-syrup',
          'coconut-cream',
          'grapefruit-soda',
          'guava-soda',
        ],
        listIDs: [
          'pineapple-juice',
          'orgeat',
          'cinnamon-syrup',
          'passion-fruit-syrup',
          'coconut-cream',
          'grapefruit-soda',
          'guava-soda',
        ],
        flatList: true,
        children: {
          'pineapple-juice': {
            name: 'Pineapple Juice',
            colSpan: 3,
            items: 1,
            include: [{ id: 'juice_pineapple' }],
            hideItems: true,
          },
          orgeat: {
            name: 'Orgeat',
            colSpan: 3,
            items: 1,
            include: [{ id: 'syrup_orgeat' }],
            hideItems: true,
          },
          'cinnamon-syrup': {
            name: 'Cinnamon Syrup',
            colSpan: 3,
            items: 1,
            include: [{ id: 'syrup_cinnamon' }],
            hideItems: true,
          },
          'passion-fruit-syrup': {
            name: 'Passion Fruit Syrup',
            colSpan: 3,
            items: 1,
            include: [{ id: 'syrup_passionfruit' }],
            hideItems: true,
          },
          'coconut-cream': {
            name: 'Coconut Cream',
            colSpan: 4,
            include: [{ id: 'cream_coconut' }],
            hideItems: true,
          },
          'grapefruit-soda': {
            name: 'Grapefruit Soda',
            colSpan: 4,
            include: [{ id: 'soda_grapefruit' }],
            hideItems: true,
          },
          'guava-soda': {
            name: 'Guava Soda',
            colSpan: 4,
            include: [{ id: 'soda_guava' }],
            hideItems: true,
          },
        },
      },
    },
  },
  liquors: {
    name: 'Hard Liquors',
    gridIDs: [
      'whiskys',
      'grain-spirits',
      'agave-spirits',
      'brandies-and-eau-de-vies',
    ],
    listIDs: [
      'whiskys',
      'grain-spirits',
      'agave-spirits',
      'brandies-and-eau-de-vies',
    ],
    children: {
      whiskys: {
        name: 'Whiskys',
        gridCols: 2,
        gridIDs: ['blended-scotch', 'other-whisky', 'islay-scotch'],
        listIDs: ['blended-scotch', 'islay-scotch', 'other-whisky'],
        children: {
          'blended-scotch': {
            name: 'Blended Scotch',
            items: 2,
            include: [{ id: 'grain_whiskey_scotch_blended' }],
          },
          'other-whisky': {
            name: 'Other Whisky',
            items: 5,
            include: [
              { id: 'grain_whiskey_irish' },
              { id: 'grain_whiskey_indian' },
              { id: 'grain_whiskey_japanese' },
              { id: 'grain_whiskey_scotch_campbeltown' },
              { id: 'grain_whiskey_scotch_speyside' },
              { id: 'grain_whiskey_scotch_highlands' },
            ],
            disableOneClickEmpty: true,
          },
          'islay-scotch': {
            name: 'Islay Scotch',
            items: 1,
            include: [{ id: 'grain_whiskey_scotch_islay' }],
          },
        },
      },
      'grain-spirits': {
        name: 'Grain Spirits',
        gridCols: 3,
        gridIDs: [
          'vodka',
          'aquavit',
          'shochu',
          'genever',
          'old-tom-gin',
          'sloe-gin',
        ],
        listIDs: [
          'vodka',
          'aquavit',
          'shochu',
          'genever',
          'old-tom-gin',
          'sloe-gin',
        ],
        children: {
          vodka: {
            name: 'Vodka',
            items: 1,
            include: [{ id: 'grain_vodka' }],
          },
          aquavit: {
            name: 'Aquavit',
            items: 1,
            include: [{ id: 'grain_aquavit' }],
          },
          shochu: {
            name: 'Shochu',
            items: 1,
            include: [{ id: 'grain_shochu' }],
          },
          genever: {
            name: 'Genever',
            items: 1,
            include: [{ id: 'grain_gin_genever' }],
          },
          'old-tom-gin': {
            name: 'Old Tom Gin',
            items: 1,
            include: [{ id: 'grain_gin_oldtom' }],
          },
          'sloe-gin': {
            name: 'Sloe Gin',
            items: 1,
            include: [{ id: 'grain_gin_sloe' }],
          },
        },
      },
      'agave-spirits': {
        name: 'Agave Spirits',
        gridCols: 2,
        gridIDs: ['tequila-reposado', 'tequila-anejo'],
        listIDs: ['tequila-reposado', 'tequila-anejo'],
        children: {
          'tequila-reposado': {
            name: 'Tequila Reposado',
            items: 1,
            include: [{ id: 'agave_tequila_reposado' }],
          },
          'tequila-anejo': {
            name: 'Tequila Anejo',
            items: 1,
            include: [{ id: 'agave_tequila_anejo' }],
          },
        },
      },
      'brandies-and-eau-de-vies': {
        name: 'Brandies & Eau-de-vies',
        gridCols: 3,
        gridIDs: [
          'pisco',
          'grappa',
          'other-brandy',
          'singani',
          'sherry-brandy',
        ],
        listIDs: [
          'pisco',
          'grappa',
          'singani',
          'sherry-brandy',
          'other-brandy',
        ],
        children: {
          pisco: {
            name: 'Pisco',
            items: 1,
            include: [{ id: 'brandy_grape_pisco' }],
          },
          grappa: {
            name: 'Grappa',
            items: 1,
            include: [{ id: 'brandy_grape_grappa' }],
          },
          'other-brandy': {
            name: 'Other Brandy',
            items: 4,
            include: [{ id: 'brandy' }],
            exclude: [
              { id: 'brandy_apple' },
              { id: 'brandy_grape_american' },
              { id: 'brandy_grape_armagnac' },
              { id: 'brandy_grape_cognac' },
              { id: 'brandy_grape_grappa' },
              { id: 'brandy_grape_pineaudescharentes' },
              { id: 'brandy_grape_pisco' },
              { id: 'brandy_grape_pommeau' },
              { id: 'brandy_grape_singani' },
              { id: 'brandy_grape_spanish' },
            ],
            disableOneClickEmpty: true,
          },
          singani: {
            name: 'Singani',
            items: 1,
            include: [{ id: 'brandy_grape_singani' }],
          },
          'sherry-brandy': {
            name: 'Sherry Brandy',
            items: 1,
            include: [{ id: 'brandy_grape_spanish' }],
          },
        },
      },
    },
  },
  liqueurs: {
    name: 'Liqueurs & Foritifed Wines',
    gridIDs: ['amari', 'liqueurs', 'foritifed-wines'],
    listIDs: ['amari', 'liqueurs', 'foritifed-wines'],
    children: {
      amari: {
        name: 'Amari',
        gridCols: 4,
        gridIDs: [
          'aperol',
          'averna',
          'china-china',
          'other-amari',
          'braulio',
          'meletti',
          'pasubio',
          'montenegro',
          'nardini',
          'rabarbaro',
          'nonino',
          'ramazzotti',
        ],
        listIDs: [
          'aperol',
          'averna',
          'braulio',
          'meletti',
          'montenegro',
          'nardini',
          'nonino',
          'ramazzotti',
          'china-china',
          'pasubio',
          'rabarbaro',
          'other-amari',
        ],
        flatList: true,
        children: {
          aperol: {
            name: 'Aperol',
            items: 1,
            ids: ['aperol'],
            hideItems: true,
          },
          averna: {
            name: 'Averna',
            items: 1,
            ids: ['amaro_averna'],
            hideItems: true,
          },
          'china-china': {
            name: 'China-China',
            items: 1,
            ids: ['amaro_ciociaro', 'bigallet_chinachina_amer'],
          },
          'other-amari': {
            name: 'Other Amari',
            items: 7,
            include: [{ id: 'liqueur_amaro' }],
            exclude: [
              { id: 'liqueur_amaro_alpine' },
              { id: 'liqueur_amaro_aperitivo' },
              { id: 'liqueur_amaro_carciofo' },
              { id: 'liqueur_amaro_fernet' },
              { id: 'liqueur_amaro_light' },
              { id: 'liqueur_amaro_rabarbaro' },
            ],
            excludeIDs: [
              'amaro_averna',
              'amaro_ciociaro',
              'bigallet_chinachina_amer',
              'ramazzotti',
              'cappelletti_pasubio_vino_amaro',
              'amaro_pasubio',
              'amaro_braulio',
              'amaro_nardini',
            ],
            bottlesOnly: true,
            disableOneClickEmpty: true,
          },
          braulio: {
            name: 'Braulio',
            ids: ['amaro_braulio'],
            hideItems: true,
          },
          meletti: {
            name: 'Meletti',
            ids: ['amaro_meletti'],
            hideItems: true,
          },
          pasubio: {
            name: 'Pasubio',
            items: 1,
            ids: ['cappelletti_pasubio_vino_amaro', 'amaro_pasubio'],
          },
          montenegro: {
            name: 'Montenegro',
            ids: ['amaro_montenegro'],
            hideItems: true,
          },
          nardini: {
            name: 'Nardini',
            ids: ['amaro_nardini'],
            hideItems: true,
          },
          rabarbaro: {
            name: 'Rabarbaro',
            items: 1,
            include: [{ id: 'liqueur_amaro_rabarbaro' }],
          },
          nonino: {
            name: 'Nonino',
            ids: ['amaro_nonino_quintessentia'],
            hideItems: true,
          },
          ramazzotti: {
            name: 'Ramazzotti',
            ids: ['ramazzotti'],
            hideItems: true,
          },
        },
      },
      liqueurs: {
        name: 'Liqueurs',
        gridCols: 3,
        gridIDs: [
          'amaretto',
          'apricot',
          'other-liqueur',
          'banana',
          'coffee-bean',
          'creme-de-cacao',
          'creme-de-menthe',
          'creme-de-violette',
          'pine',
          'peach',
          'pear',
          'coconut',
          'passion-fruit',
          "pimm's",
          'strega',
          'galliano',
          'drambuie',
        ],
        listIDs: [
          'amaretto',
          'apricot',
          'banana',
          'coconut',
          'coffee-bean',
          'creme-de-cacao',
          'creme-de-menthe',
          'creme-de-violette',
          'passion-fruit',
          'pear',
          'peach',
          "pimm's",
          'pine',
          'other-liqueur',
          'strega',
          'galliano',
          'drambuie',
        ],
        flatList: true,
        children: {
          amaretto: {
            name: 'Amaretto',
            items: 1,
            include: [{ id: 'liqueur_amaretto' }],
          },
          apricot: {
            name: 'Apricot',
            items: 1,
            include: [{ id: 'liqueur_apricot' }],
          },
          'other-liqueur': {
            name: 'Other Liqueur',
            items: 4,
            include: [{ id: 'liqueur' }],
            exclude: [
              { id: 'liqueur_maraschino' },
              { id: 'liqueur_orange' },
              { id: 'liqueur_absinthe' },
              { id: 'liqueur_elderflower' },
              { id: 'liqueur_cherryheering' },
              { id: 'liqueur_allspice' },
              { id: 'liqueur_amaro' },
              { id: 'liqueur_amaretto' },
              { id: 'liqueur_apricot' },
              { id: 'liqueur_banana' },
              { id: 'liqueur_coffeebean' },
              { id: 'liqueur_cremedecacao' },
              { id: 'liqueur_cremedementhe' },
              { id: 'liqueur_cremedeviolette' },
              { id: 'liqueur_pine' },
              { id: 'liqueur_falernum' },
              { id: 'liqueur_fir' },
              { id: 'liqueur_coconut' },
              { id: 'liqueur_passionfruit' },
              { id: 'liqueur_pimms' },
              { id: 'liqueur_rich' },
            ],
            excludeIDs: [
              'benedictine',
              'yellow_chartreuse',
              'green_chartreuse',
              'john_d_taylors_velvet_falernum',
              'st_elizabeth_allspice_dram',
              'dolin_genepy_des_alpes',
              'sapins',
              'strega',
              'galliano_lautentico',
              'drambuie',
            ],
            disableOneClickEmpty: true,
          },
          banana: {
            name: 'Banana',
            items: 1,
            include: [{ id: 'liqueur_banana' }],
          },
          'coffee-bean': {
            name: 'Coffee',
            items: 1,
            include: [{ id: 'liqueur_coffeebean' }],
          },
          'creme-de-cacao': {
            name: 'Crème de Cacao',
            items: 1,
            include: [{ id: 'liqueur_cremedecacao' }],
          },
          'creme-de-menthe': {
            name: 'Crème de Menthe',
            items: 1,
            include: [{ id: 'liqueur_cremedementhe' }],
          },
          'creme-de-violette': {
            name: 'Crème de Violette',
            items: 1,
            include: [{ id: 'liqueur_cremedeviolette' }],
          },
          pine: {
            name: 'Pine',
            items: 1,
            include: [{ id: 'liqueur_pine' }, { id: 'liqueur_fir' }],
            ids: ['dolin_genepy_des_alpes', 'sapins'],
            bottlesOnly: true,
          },
          peach: {
            name: 'Peach',
            items: 1,
            include: [{ id: 'liqueur_peach' }],
          },
          pear: {
            name: 'Pear',
            items: 1,
            include: [{ id: 'liqueur_pear' }],
          },
          coconut: {
            name: 'Coconut',
            include: [{ id: 'liqueur_coconut' }],
          },
          'passion-fruit': {
            name: 'Passion Fruit',
            include: [{ id: 'liqueur_passionfruit' }],
          },
          "pimm's": {
            name: "Pimm's",
            include: [{ id: 'liqueur_pimms' }],
          },
          strega: {
            name: 'Strega',
            ids: ['strega'],
            hideItems: true,
          },
          galliano: {
            name: 'Galliano',
            ids: ['galliano_lautentico'],
            hideItems: true,
          },
          drambuie: {
            name: 'Drambuie',
            ids: ['drambuie'],
            hideItems: true,
          },
        },
      },
      'foritifed-wines': {
        name: 'Foritifed Wines',
        gridCols: 3,
        gridIDs: [
          'oloroso-sherry',
          'pedro-ximenez-sherry',
          'cream-sherry',
          'port',
          'madeira',
          'aperitifs',
        ],
        listIDs: [
          'oloroso-sherry',
          'pedro-ximenez-sherry',
          'cream-sherry',
          'port',
          'madeira',
          'aperitifs',
        ],
        children: {
          'oloroso-sherry': {
            name: 'Oloroso Sherry',
            items: 1,
            include: [{ id: 'fortifiedwine_sherry_oloroso' }],
          },
          'pedro-ximenez-sherry': {
            name: 'P.X. Sherry',
            items: 1,
            include: [{ id: 'fortifiedwine_sherry_pedroximenez' }],
          },
          'cream-sherry': {
            name: 'Cream Sherry',
            items: 1,
            include: [{ id: 'fortifiedwine_sherry_cream' }],
          },
          port: {
            name: 'Port',
            items: 2,
            include: [{ id: 'fortifiedwine_port' }],
          },
          madeira: {
            name: 'Madeira',
            items: 2,
            include: [{ id: 'fortifiedwine_madeira' }],
          },
          aperitifs: {
            name: 'Apéritifs',
            items: 2,
            include: [
              { id: 'fortifiedwine_ambrevermouth' },
              { id: 'fortifiedwine_aperitif' },
            ],
            excludeIDs: [
              'lillet_blanc',
              'cocchi_americano_bianco',
              'cap_corse_blanc_quinquina',
            ],
            disableOneClickEmpty: true,
          },
        },
      },
    },
  },
}
